In this assignement, feel free to use the sparse module from scipy.

Use the cell below for your imports.

In [1]:
import numpy as np
from scipy.sparse import coo_matrix, csr_matrix
from scipy.sparse.linalg import spsolve

implement the function mat_mul_coo that takes two sparse matrices in coo and returns their product.

In [2]:
def mat_mul_coo(a: coo_matrix, b: coo_matrix) -> coo_matrix:
    if a.shape[1] != b.shape[0]:
        raise ValueError("Matrix dimensions do not match for multiplication")

    a_csr = csr_matrix(a)
    b_csr = csr_matrix(b)

    result = a_csr.dot(b_csr).tocoo()
    result.sum_duplicates()

    return result

implement the function mat_mul_csr that takes two sparse matrices in csr format and returns their product.

In [3]:
def mat_mul_csr(a: csr_matrix, b: csr_matrix) -> csr_matrix:
    if a.shape[1] != b.shape[0]:
        raise ValueError("Matrix dimensions do not match for multiplication")

    result = a.dot(b)

    return result

implement a function solve_lin_sys that takes a matrix A in csr format and a vector b as a numpy array and solves the system Ax = b.

In [4]:
def solve_lin_sys(A: csr_matrix, b: np.ndarray) -> np.ndarray:
    x = spsolve(A, b)
    return x

In [5]:
data = np.array([1, 2, 3])
row  = np.array([0, 1, 2])
col  = np.array([0, 1, 2])

sparse_matrix = coo_matrix((data, (row, col)))

In [6]:
sparse_matrix.todense()

matrix([[1, 0, 0],
        [0, 2, 0],
        [0, 0, 3]])

In [7]:
a = mat_mul_coo(sparse_matrix,sparse_matrix)

In [8]:
a.todense()

matrix([[1, 0, 0],
        [0, 4, 0],
        [0, 0, 9]], dtype=int32)

In [9]:
data = np.array([1, 2, 3, 4, 5, 6])
col_indices = np.array([0, 2, 3, 1, 2, 3])
row_pointers = np.array([0, 3, 5, 6])

sparse_matrix = csr_matrix((data, col_indices, row_pointers))

dense_matrix = sparse_matrix.toarray()

print(dense_matrix)

[[1 0 2 3]
 [0 4 5 0]
 [0 0 0 6]]


In [10]:
dense_matrix = np.array([[1, 0, 0], [0, 2, 0], [0, 0, 3]])

# create a CSR matrix from the dense matrix
csr_matrix = csr_matrix(dense_matrix)

# print the CSR matrix
print(csr_matrix)

  (0, 0)	1
  (1, 1)	2
  (2, 2)	3


In [11]:
b = mat_mul_csr(csr_matrix,csr_matrix)

In [12]:
b.todense()

matrix([[1, 0, 0],
        [0, 4, 0],
        [0, 0, 9]], dtype=int32)